import nltk
from typing import Union
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI()

origins = ["http://localhost:3000"]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


nltk.download('punkt')

nltk.download('vader_lexicon')

from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk.tokenize import word_tokenize
from mongotest import getKeywordCaptions


sia = SentimentIntensityAnalyzer()

custom_lexicon = {
    'admiration': 1.5,
    'affection': 1.5,
    'approval': 1.5,
    'gratitude': 1.5,
    'liking': 1.5,
    'love': 1.5,
    'praise': 1.5,
    'satisfaction': 1.5,
    'contentment': 1.5,
    'delight': 1.5,
    'happiness': 1.5,
    'joy': 1.5,
    'pleasure': 1.5,
    'optimism': 1.5,
    'hope': 1.5,
    'confidence': 1.5,
    'faith': 1.5,
    'inspiration': 1.5,
    'motivation': 1.5,
    'enthusiasm': 1.5,
    'passion': 1.5,
    'ambition': 1.5,
    'interest': 1.0,
    'curiosity': 1.0,
    'wonder': 1.0,
    'fascination': 1.0,
    'amusement': 1.0,
    'daring': 1.0,
    'honor': 1.0,
    'respect': 1.0,
    'trust': 1.0,
    'excitement': 1.0,
    'eagerness': 1.0,
    'admiration': 1.0,
    'appreciation': 1.0,
    'wonder': 1.0,
    'awe': 1.0,
    'fascination': 1.0,
    'empathy': 1.0,
    'kindness': 1.0,
    'sympathy': 1.0,
    'goodness': 1.0,
    'compassion': 1.0,
    'serenity': 1.0,
    'relaxation': 1.0,
    'relief': 1.0,
    'contentment': 1.0,
    'excitement': 1.0,
    'interest': 1.0,
    'curiosity': 1.0,
    'amazement': 1.0,
    'hope': 1.0,
    'motivation': 1.0,
    'relief': 1.0,
    'peace': 1.0,
    'tolerance': 1.0,
    'forgiveness': 1.0,
    'calmness': 1.0,
    'warmth': 1.0,
    'comfort': 1.0,
    'ease': 1.0,
    'tranquility': 1.0,
    'confidence': 1.0,
    'euphoria': 1.0,
    'bliss': 1.0,
    'gratitude': 1.0,
    'inspiration': 1.0,
    'ambition': 1.0,
    'enthusiasm': 1.0,
    'drive': 1.0,
    'energy': 1.0,
    'intimacy': 1.0,
    'tenderness': 1.0,
    'affection': 1.0,
    'eagerness': 1.0,
    'persistence': 1.0,
    'amusement': 1.0,
    'fun': 1.0,
    'relaxation': 1.0,
    'surprise': 1.0,
    'excitement': 1.0,
    'thrill': 1.0,
    'interest': 1.0,
    'curiosity': 1.0,
    'wonder': 1.0,
    'relief': 1.0,
    'amazement': 1.0,
    'awe': 1.0,
    'compassion': 1.0,
    'tolerance': 1.0,
    'kindness': 1.0,
    'friendliness': 1.0,
    'humanity': 1.0,
    'charity': 1.0,
    'generosity': 1.0,
    'peace': 1.0,
    'patience': 1.0,
    'confidence': 1.0,
    'euphoria': 1.0,
    'kindness': 1.0,
    'sympathy': 1.0,
    'goodness': 1.0,
    'selflessness': 1.0,
    'tolerance': 1.0,
    'forgiveness': 1.0,
    'comfort': 1.0,
    'ease': 1.0,
    'compassion': 1.0,
    'empathy': 1.0,
    'contentment': 1.0,
    'serenity': 1.0,
    'relaxation': 1.0,
    'peace': 1.0,
    'relief': 1.0,
    'relaxation': 1.0,
    'serenity': 1.0,
    'delight': 1.0,
    'elation': 1.0,
    'bliss': 1.0,
    'love': 1.0,
    'passion': 1.0,
    'optimism': 1.0,
    'enthusiasm': 1.0,
    'hope': 1.0,
    'inspiration': 1.0,
    'motivation': 1.0,
    'ambition': 1.0,
    'drive': 1.0,
    'energy': 1.0,
    'excitement': 1.0,
    'interest': 1.0,
    'curiosity': 1.0,
    'wonder': 1.0,
    'fascination': 1.0,
    'amusement': 1.0,
    'daring': 1.0,
    'confidence': 1.0,
    'eagerness': 1.0,
    'persistence': 1.0,
    'optimism': 1.0,
    'joy': 1.0,
    'happiness': 1.0,
    'wonder': 1.0,
    'surprise': 1.0,
    'enthusiasm': 1.0,
    'thrill': 1.0,
    'hope': 1.0,
    'inspiration': 1.0,
    'motivation': 1.0,
    'amusement': 1.0,
    'fun': 1.0,
    'pleasure': 1.0,
    'relief': 1.0,
    'calmness': 1.0,
    'comfort': 1.0,
    'interest': 1.0,
    'curiosity': 1.0,
    'wonder': 1.0,
    'amazement': 1.0,
    'awe': 1.0,
    'compassion': 1.0,
    'tolerance': 1.0,
    'kindness': 1.0,
    'friendliness': 1.0,
    'humanity': 1.0,
    'charity': 1.0,
    'generosity': 1.0,
    'peace': 1.0,
    'patience': 1.0,
    'confidence': 1.0,
    'euphoria': 1.0,
    'kindness': 1.0,
    'sympathy': 1.0,
    'goodness': 1.0,
    'selflessness': 1.0,
    'tolerance': 1.0,
    'forgiveness': 1.0,
    'comfort': 1.0,
    'ease': 1.0,
    'compassion': 1.0,
    'empathy': 1.0,
    'contentment': 1.0,
    'serenity': 1.0,
    'relaxation': 1.0,
    'peace': 1.0,
    'relief': 1.0,
    'relaxation': 1.0,
    'serenity': 1.0,
    'delight': 1.0,
    'elation': 1.0,
    'bliss': 1.0,
    'love': 1.0,
    'passion': 1.0,
    'optimism': 1.0,
    'enthusiasm': 1.0,
    'hope': 1.0,
    'inspiration': 1.0,
    'motivation': 1.0,
    'ambition': 1.0,
    'drive': 1.0,
    'energy': 1.0,
    'excitement': 1.0,
    'interest': 1.0,
    'curiosity': 1.0,
    'wonder': 1.0,
    'fascination': 1.0,
    'amusement': 1.0,
    'daring': 1.0,
    'confidence': 1.0,
    'eagerness': 1.0,
    'persistence': 1.0,
    'optimism': 1.0,
    'joy': 1.0,
    'happiness': 1.0,
    'wonder': 1.0,
    'surprise': 1.0,
    'enthusiasm': 1.0,
    'thrill': 1.0,
    'hope': 1.0,
    'inspiration': 1.0,
    'motivation': 1.0,
    'amusement': 1.0,
    'fun': 1.0,
    'pleasure': 1.0,
    'relief': 1.0,
    'calmness': 1.0,
    'comfort': 1.0,
    'interest': 1.0,
    'curiosity': 1.0,
    'wonder': 1.0,
    'amazement': 1.0,
    'awe': 1.0,
    'compassion': 1.0,
    'tolerance': 1.0,
    'kindness': 1.0,
    'friendliness': 1.0,
    'humanity': 1.0,
    'charity': 1.0,
    'generosity': 1.0,
    'peace': 1.0,
    'patience': 1.0,
    'confidence': 1.0,
    'euphoria': 1.0,
    'kindness': 1.0,
    'sympathy': 1.0,
    'goodness': 1.0,
    'selflessness': 1.0,
    'tolerance': 1.0,
    'forgiveness': 1.0,
    'comfort': 1.0,
    'ease': 1.0,
    'compassion': 1.0,
    'empathy': 1.0,
    'contentment': 1.0,
    'serenity': 1.0,
    'relaxation': 1.0,
    'peace': 1.0,
    'relief': 1.0,
    'relaxation': 1.0,
    'serenity': 1.0,
    'delight': 1.0,
    'elation': 1.0,
    'bliss': 1.0,
    'kindness': 1.0,
    'sympathy': 1.0,
    'goodness': 1.0,
    'selflessness': 1.0,
    'patience': 1.0,
    'tolerance': 1.0,
    'forgiveness': 1.0,
    'peace': 1.0,
    'calmness': 1.0,
    'comfort': 1.0,
    'ease': 1.0,
    'compassion': 1.0,
    'empathy': 1.0,
    'contentment': 1.0,
    'serenity': 1.0,
    'relaxation': 1.0,
    'peace': 1.0,
    'relief': 1.0,
    'relaxation': 1.0,
    'serenity': 1.0,
    'delight': 1.0,
    'elation': 1.0,
    'bliss': 1.0,
    'sadness': -1.5,
    'anger': -1.5,
    'fear': -1.5,
    'disgust': -1.5,
    'loneliness': -1.5,
    'disappointment': -1.5,
    'grief': -1.5,
    'guilt': -1.5,
    'shame': -1.5,
    'regret': -1.5,
    'pain': -1.5,
    'anxiety': -1.5,
    'stress': -1.5,
    'confusion': -1.5,
    'frustration': -1.5,
    'boredom': -1.5,
    'indifference': -1.5,
    'disinterest': -1.5,
    'apathy': -1.5,
    'ennui': -1.5,
    'irritation': -1.5,
    'hostility': -1.5,
    'jealousy': -1.5,
    'envy': -1.5,
    'greed': -1.5,
    'selfishness': -1.5,
    'bitterness': -1.5,
    'resentment': -1.5,
    'hate': -1.5,
    'indifference': -1.5,
    'neglect': -1.5,
    'rejection': -1.5,
    'isolation': -1.5,
    'hopelessness': -1.5,
    'despair': -1.5,
    'grief': -1.5,
    'remorse': -1.5,
    'anxiety': -1.5,
    'fear': -1.5,
    'stress': -1.5,
    'panic': -1.5,
    'tension': -1.5,
    'disgust': -1.5,
    'loathing': -1.5,
    'abhorrence': -1.5,
    'regret': -1.5,
    'remorse': -1.5,
    'shame': -1.5,
    'embarrassment': -1.5,
    'nervousness': -1.5,
    'discomfort': -1.5,
    'sorrow': -1.5,
    'melancholy': -1.5,
    'dissatisfaction': -1.5,
    'frustration': -1.5,
    'discontent': -1.5,
    'anger': -1.5,
    'rage': -1.5,
    'hostility': -1.5,
    'irritation': -1.5,
    'annoyance': -1.5,
    'bitterness': -1.5,
    'distrust': -1.5,
    'paranoia': -1.5,
    'guilt': -1.5,
    'remorse': -1.5,
    'shame': -1.5,
    'self-pity': -1.5,
    'jealousy': -1.5,
    'envy': -1.5,
    'greed': -1.5,
    'selfishness': -1.5,
    'malice': -1.5,
    'hatred': -1.5,
    'cruelty': -1.5,
    'neglect': -1.5,
    'rejection': -1.5,
    'abandonment': -1.5,
    'isolation': -1.5,
    'hopelessness': -1.5,
    'despair': -1.5,
    'shock': -1.5,
    'disbelief': -1.5,
    'confusion': -1.5,
    'fear': -1.5,
    'disorientation': -1.5,
    'surprise': -1.5,
    'horror': -1.5,
    'revulsion': -1.5,
    'disgust': -1.5,
    'indifference': -1.5,
    'apathy': -1.5,
    'boredom': -1.5,
    'ennui': -1.5,
    'disinterest': -1.5,
    'insomnia': -1.5,
    'fatigue': -1.5,
    'weariness': -1.5,
    'exhaustion': -1.5,
    'irritation': -1.5,
    'annoyance': -1.5,
    'frustration': -1.5,
    'anger': -1.5,
    'rage': -1.5,
    'hostility': -1.5,
    'jealousy': -1.5,
    'envy': -1.5,
    'greed': -1.5,
    'selfishness': -1.5,
    'bitterness': -1.5,
    'resentment': -1.5,
    'hate': -1.5,
    'indifference': -1.5,
    'neglect': -1.5,
    'rejection': -1.5,
    'isolation': -1.5,
    'hopelessness': -1.5,
    'despair': -1.5,
    'grief': -1.5,
    'remorse': -1.5,
    'anxiety': -1.5,
    'fear': -1.5,
    'stress': -1.5,
    'panic': -1.5,
    'tension': -1.5,
    'disgust': -1.5,
    'loathing': -1.5,
    'abhorrence': -1.5,
    'regret': -1.5,
    'remorse': -1.5,
    'shame': -1.5,
    'embarrassment': -1.5,
    'nervousness': -1.5,
    'discomfort': -1.5,
    'sorrow': -1.5,
    'melancholy': -1.5,
    'dissatisfaction': -1.5,
    'frustration': -1.5,
    'discontent': -1.5,
    'anger': -1.5,
    'rage': -1.5,
    'hostility': -1.5,
    'irritation': -1.5,
    'annoyance': -1.5,
    'bitterness': -1.5,
    'distrust': -1.5,
    'paranoia': -1.5,
    'guilt': -1.5,
    'remorse': -1.5,
    'shame': -1.5,
    'self-pity': -1.5,
    'jealousy': -1.5,
    'envy': -1.5,
    'greed': -1.5,
    'selfishness': -1.5,
    'malice': -1.5,
    'hatred': -1.5,
    'cruelty': -1.5,
    'neglect': -1.5,
    'rejection': -1.5,
    'abandonment': -1.5,
    'isolation': -1.5,
    'hopelessness': -1.5,
    'despair': -1.5,
    'shock': -1.5,
    'disbelief': -1.5,
    'confusion': -1.5,
    'fear': -1.5,
    'disorientation': -1.5,
    'surprise': -1.5,
    'horror': -1.5,
    'revulsion': -1.5,
    'disgust': -1.5,
    'indifference': -1.5,
    'apathy': -1.5,
    'boredom': -1.5,
    'ennui': -1.5,
    'disinterest': -1.5,
    'insomnia': -1.5,
    'fatigue': -1.5,
    'weariness': -1.5,
    'exhaustion': -1.5,
    'irritation': -1.5,
    'annoyance': -1.5,
    'frustration': -1.5,
    'anger': -1.5,
    'rage': -1.5,
    'hostility': -1.5,
    'jealousy': -1.5,
    'envy': -1.5,
    'greed': -1.5,
    'selfishness': -1.5,
    'bitterness': -1.5,
    'resentment': -1.5,
    'hate': -1.5,
    'indifference': -1.5,
    'neglect': -1.5,
    'rejection': -1.5,
    'isolation': -1.5,
    'hopelessness': -1.5,
    'despair': -1.5,
    'grief': -1.5,
    'remorse': -1.5,
    'anxiety': -1.5,
    'fear': -1.5,
    'stress': -1.5,
    'panic': -1.5,
    'tension': -1.5,
    'disgust': -1.5,
    'loathing': -1.5,
    'abhorrence': -1.5,
    'regret': -1.5,
    'remorse': -1.5,
    'shame': -1.5,
    'embarrassment': -1.5,
    'nervousness': -1.5,
    'discomfort': -1.5,
    'sorrow': -1.5,
    'melancholy': -1.5,
    'dissatisfaction': -1.5,
    'frustration': -1.5,
    'discontent': -1.5,
    'anger': -1.5,
    'rage': -1.5,
    'hostility': -1.5,
    'irritation': -1.5,
    'annoyance': -1.5,
    'bitterness': -1.5,
    'distrust': -1.5,
    'paranoia': -1.5,
    'guilt': -1.5,
    'remorse': -1.5,
    'shame': -1.5,
    'self-pity': -1.5,
    'jealousy': -1.5,
    'envy': -1.5,
    'greed': -1.5,
    'selfishness': -1.5,
    'malice': -1.5,
    'hatred': -1.5,
    'cruelty': -1.5,
    'neglect': -1.5,
    'rejection': -1.5,
    'abandonment': -1.5,
    'isolation': -1.5,
    'hopelessness': -1.5,
    'despair': -1.5,
    'shock': -1.5,
    'disbelief': -1.5,
    'confusion': -1.5,
    'fear': -1.5,
    'disorientation': -1.5,
    'surprise': -1.5,
    'horror': -1.5,
    'revulsion': -1.5,
    'disgust': -1.5,
    'indifference': -1.5,
    'apathy': -1.5,
    'boredom': -1.5,
    'ennui': -1.5,
    'disinterest': -1.5,
    'insomnia': -1.5,
    'fatigue': -1.5,
    'weariness': -1.5,
    'exhaustion': -1.5,
    'irritation': -1.5,
    'annoyance': -1.5,
    'frustration': -1.5,
    'anger': -1.5,
    'rage': -1.5,
    'hostility': -1.5,
    'jealousy': -1.5,
    'envy': -1.5,
    'greed': -1.5,
    'selfishness': -1.5,
    'bitterness': -1.5,
    'resentment': -1.5,
    'hate': -1.5,
    'indifference': -1.5,
    'neglect': -1.5,
    'rejection': -1.5,
    'isolation': -1.5,
    'hopelessness': -1.5,
    'despair': -1.5,
    'grief': -1.5,
    'remorse': -1.5,
    'anxiety': -1.5,
    'fear': -1.5,
    'stress': -1.5,
    'panic': -1.5,
    'tension': -1.5,
    'disgust': -1.5,
    'loathing': -1.5,
    'abhorrence': -1.5,
    'regret': -1.5,
    'remorse': -1.5,
    'shame': -1.5,
    'embarrassment': -1.5,
    'nervousness': -1.5,
    'discomfort': -1.5,
    'sorrow': -1.5,
    'melancholy': -1.5,
    'dissatisfaction': -1.5,
    'frustration': -1.5,
    'discontent': -1.5,
    'anger': -1.5,
    'rage': -1.5,
    'hostility': -1.5,
    'irritation': -1.5,
    'annoyance': -1.5,
    'bitterness': -1.5,
    'distrust': -1.5,
    'paranoia': -1.5,
    'guilt': -1.5,
    'remorse': -1.5,
    'shame': -1.5,
    'self-pity': -1.5,
    'jealousy': -1.5,
    'envy': -1.5,
    'greed': -1.5,
    'selfishness': -1.5,
    'malice': -1.5,
    'hatred': -1.5,
    'cruelty': -1.5,
    'neglect': -1.5,
    'rejection': -1.5,
    'abandonment': -1.5,
    'isolation': -1.5,
    'hopelessness': -1.5,
    'despair': -1.5,
    'shock': -1.5,
    'disbelief': -1.5,
    'confusion': -1.5,
    'fear': -1.5,
    'disorientation': -1.5,
    'surprise': -1.5,
    'horror': -1.5,
    'revulsion': -1.5,
    'disgust': -1.5,
    'indifference': -1.5,
    'apathy': -1.5,
    'boredom': -1.5,
    'ennui': -1.5,
    'disinterest': -1.5,
    'insomnia': -1.5,
    'fatigue': -1.5,
    'weariness': -1.5,
    'exhaustion': -1.5,
    'irritation': -1.5,
    'annoyance': -1.5,
    'frustration': -1.5,
    'anger': -1.5,
    'rage': -1.5,
    'hostility': -1.5,
    'jealousy': -1.5,
    'envy': -1.5,
    'greed': -1.5,
    'selfishness': -1.5,
    'bitterness': -1.5,
    'resentment': -1.5,
    'hate': -1.5,
    'indifference': -1.5,
    'neglect': -1.5,
    'rejection': -1.5,
    'isolation': -1.5,
    'hopelessness': -1.5,
    'despair': -1.5,
    'grief': -1.5,
    'remorse': -1.5,
    'anxiety': -1.5,
    'fear': -1.5,
    'stress': -1.5,
    'panic': -1.5,
    'tension': -1.5,
    'disgust': -1.5,
    'loathing': -1.5,
    'abhorrence': -1.5,
    'regret': -1.5,
    'remorse': -1.5,
    'shame': -1.5,
    'embarrassment': -1.5,
    'nervousness': -1.5,
    'discomfort': -1.5,
    'sorrow': -1.5,
    'melancholy': -1.5,
    'dissatisfaction': -1.5,
    'frustration': -1.5,
    'discontent': -1.5,
    'anger': -1.5,
    'rage': -1.5,
    'hostility': -1.5,
    'irritation': -1.5,
    'annoyance': -1.5,
    'bitterness': -1.5,
    'distrust': -1.5,
    'paranoia': -1.5,
    'guilt': -1.5,
    'remorse': -1.5,
    'shame': -1.5,
    'self-pity': -1.5,
    'jealousy': -1.5,
    'envy': -1.5,
    'greed': -1.5,
    'selfishness': -1.5,
    'malice': -1.5,
    'hatred': -1.5,
    'cruelty': -1.5,
    'neglect': -1.5,
    'rejection': -1.5,
    'abandonment': -1.5,
    'isolation': -1.5,
    'hopelessness': -1.5,
    'despair': -1.5,
    'shock': -1.5,
    'disbelief': -1.5,
    'confusion': -1.5,
    'fear': -1.5,
    'disorientation': -1.5,
    'surprise': -1.5,
    'horror': -1.5,
    'revulsion': -1.5,
    'disgust': -1.5,
    'indifference': -1.5,
    'apathy': -1.5,
    'boredom': -1.5,
    'ennui': -1.5,
    'disinterest': -1.5,
    'insomnia': -1.5,
    'fatigue': -1.5,
    'weariness': -1.5,
    'exhaustion': -1.5
}

sia.lexicon.update(custom_lexicon)


negation_words = [
    "Not",
    "No",
    "Neither",
    "Nor",
    "None",
    "Never",
    "Nothing",
    "Nobody",
    "Nowhere",
    "Hardly",
    "Barely",
    "Rarely",
    "Scarcely",
    "Seldom",
    "Few",
    "Little",
    "Lack",
    "Lacking",
    "Without",
    "Absence",
    "Negative",
    "Opposite",
    "Reversal",
    "Contrary",
    "Antithesis",
    "Anti",
    "Deny",
    "Refuse",
    "Reject",
    "Resist",
    "Block",
    "Prevent",
    "Stop",
    "Inhibit",
    "Halt",
    "Counter",
    "Contradict",
    "Contra",
    "However",
    "Nevertheless",
    "Nonetheless",
    "Although",
    "Though",
    "Yet",
    "But",
    "Despite",
    "In spite of",
    "Even though",
    "Although",
    "While",
    "Don't",
    "Doesn't",
    "Didn't",
    "Can't",
    "Couldn't",
    "Won't",
    "Wouldn't",
    "Shouldn't",
    "Mustn't",
    "Isn't",
    "Aren't",
    "Hasn't",
    "Haven't",
    "Hadn't",
    "Wasn't",
    "Weren't",
    "Isn't",
    "Wain't",
    "Needn't",
    "Nor",
    "Hardly",
    "Barely",
    "Scarcely",
    "Seldom",
    "Few",
    "Little",
    "Lack",
    "Lacking",
    "Without",
    "Absence",
    "Negative",
    "Opposite",
    "Reversal",
    "Contrary",
    "Antithesis",
    "Anti",
    "Deny",
    "Refuse",
    "Reject",
    "Resist",
    "Block",
    "Prevent",
    "Stop",
    "Inhibit",
    "Halt",
    "Counter",
    "Contradict",
    "Contra",
    "However",
    "Nevertheless"
]



def adjust_for_negation(sentiments, text):
    words = word_tokenize(text)
    for i in range(len(words)):
        if words[i].lower() in negation_words:
            j = i + 1
            while j < len(words) and words[j] not in [',', '.', '!', '?', ';']:
                if words[j].lower() in custom_lexicon:
                    sentiments['compound'] *= -1  
                    break
                j += 1

def restaurant_review_rating(review):
    # Analyze the sentiment of the review
    sentiment_scores = sia.polarity_scores(review)

   
    adjust_for_negation(sentiment_scores, review)

    
    compound_score = sentiment_scores['compound']
    min_score = -1.0
    max_score = 1.0
    scaled_rating = 1 + 4 * (compound_score - min_score) / (max_score - min_score)

    # Ensure the rating is within the 1-5 range
    final_rating = max(1, min(5, scaled_rating))

    return final_rating


@app.get("/rating/{keyword}")
def rating(keyword: str):
    review = getKeywordCaptions(keyword)
    rating = restaurant_review_rating(review)
    return {"keyword": keyword, "rating": rating}

